-- ============================================================
-- FILE: backend/prisma/migrations/20260903134139_init_ops_erp/migration.sql
-- CONSTRUCTION ORDER: #10
-- HOW: THIS FILE WAS NOT WRITTEN BY HAND.
--      It was automatically generated by running:
--        npx prisma migrate dev --name init_ops_erp
--      Prisma compared schema.prisma to the current database state (empty),
--      computed the full SQL diff, wrote this file, AND applied it to the database.
--      The timestamp prefix (20260903134139) was auto-generated from the current date/time.
-- WHY: This file is the permanent record of what was done to the database.
--      It is committed to git alongside schema.prisma so that:
--        1. Any developer cloning the repo can run `npx prisma migrate deploy`
--           to create the exact same database schema
--        2. CI pipelines apply the same migrations to fresh test databases
--        3. Production deployments (Dockerfile CMD) apply migrations automatically
-- IMPORTANT: Never edit this file manually. If you need to change the schema,
--            edit schema.prisma and run `npx prisma migrate dev --name <description>`
--            to generate a NEW migration file. Old migrations are immutable.
-- ============================================================

-- ── Step 1: Create PostgreSQL ENUM types ─────────────────────────────────────
-- These match the `enum` declarations in schema.prisma.
-- PostgreSQL ENUM types are stored as labels — they take less space than VARCHAR
-- and are validated at the database level (you cannot insert 'UNKNOWN' into a Role column).
-- Each enum value in schema.prisma becomes a label in the PostgreSQL ENUM type.

-- CreateEnum
-- Role maps to: Role { ADMIN OPERATIONS SALES } in schema.prisma
CREATE TYPE "Role" AS ENUM ('ADMIN', 'OPERATIONS', 'SALES');

-- CreateEnum
-- WorkOrderStatus maps to: WorkOrderStatus { ASSIGNED IN_PROGRESS COMPLETED }
CREATE TYPE "WorkOrderStatus" AS ENUM ('ASSIGNED', 'IN_PROGRESS', 'COMPLETED');

-- CreateEnum
-- TransferStatus maps to: TransferStatus { REQUESTED DISPATCHED RECEIVED CANCELLED }
CREATE TYPE "TransferStatus" AS ENUM ('REQUESTED', 'DISPATCHED', 'RECEIVED', 'CANCELLED');

-- CreateEnum
-- OrderStatus maps to: OrderStatus { PENDING CONFIRMED CANCELLED }
CREATE TYPE "OrderStatus" AS ENUM ('PENDING', 'CONFIRMED', 'CANCELLED');

-- CreateEnum
-- TransactionType maps to: TransactionType { IN OUT }
CREATE TYPE "TransactionType" AS ENUM ('IN', 'OUT');

-- ── Step 2: Create all tables ─────────────────────────────────────────────────
-- Tables are created in dependency order: referenced tables first.
-- Foreign keys are added AFTER all tables exist (see Step 4).

-- CreateTable
-- Matches model User in schema.prisma.
-- "id" TEXT maps to Prisma's String @id.
-- TIMESTAMP(3) = timestamp with 3ms precision.
-- "role" uses the "Role" ENUM type defined above.
-- DEFAULT 'SALES' matches @default(SALES) in schema.prisma.
CREATE TABLE "users" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "role" "Role" NOT NULL DEFAULT 'SALES',
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    -- Primary key constraint. CONSTRAINT name is auto-generated by Prisma.
    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
-- Matches model Location in schema.prisma.
-- "address" TEXT (no NOT NULL) — nullable, matches String? in schema.
CREATE TABLE "locations" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "address" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "locations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
-- Matches model Item in schema.prisma.
-- DECIMAL(10,2) matches @db.Decimal(10, 2) — exact decimal arithmetic for prices.
CREATE TABLE "items" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "sku" TEXT NOT NULL,
    "category" TEXT,
    "unitPrice" DECIMAL(10,2) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
-- Matches model Inventory in schema.prisma.
-- DEFAULT 'DEFAULT' matches batchNumber String @default("DEFAULT").
-- Both physicalQty and reservedQty default to 0 — a new row has no stock.
CREATE TABLE "inventory" (
    "id" TEXT NOT NULL,
    "itemId" TEXT NOT NULL,
    "locationId" TEXT NOT NULL,
    "batchNumber" TEXT NOT NULL DEFAULT 'DEFAULT',
    "physicalQty" INTEGER NOT NULL DEFAULT 0,
    "reservedQty" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "inventory_pkey" PRIMARY KEY ("id")
);

-- CreateTable
-- Matches model InventoryTransaction in schema.prisma.
-- "referenceKey" TEXT (nullable, no NOT NULL) — matches String? in schema.
-- "transactionType" uses the "TransactionType" ENUM.
CREATE TABLE "inventory_transactions" (
    "id" TEXT NOT NULL,
    "inventoryId" TEXT NOT NULL,
    "transactionType" "TransactionType" NOT NULL,
    "quantity" INTEGER NOT NULL,
    "reason" TEXT,
    "referenceKey" TEXT,
    "createdById" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "inventory_transactions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
-- Matches model WorkOrder in schema.prisma.
-- "startedAt" and "completedAt" are nullable (no NOT NULL) — set only as status progresses.
-- "itemName" and "itemSku" are NOT NULL — snapshot fields always captured at creation.
CREATE TABLE "work_orders" (
    "id" TEXT NOT NULL,
    "workOrderNumber" TEXT NOT NULL,
    "locationId" TEXT NOT NULL,
    "itemId" TEXT NOT NULL,
    "requiredQty" INTEGER NOT NULL,
    "assignedToId" TEXT NOT NULL,
    "status" "WorkOrderStatus" NOT NULL DEFAULT 'ASSIGNED',
    "notes" TEXT,
    "createdById" TEXT NOT NULL,
    "startedAt" TIMESTAMP(3),
    "completedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "itemName" TEXT NOT NULL,
    "itemSku" TEXT NOT NULL,

    CONSTRAINT "work_orders_pkey" PRIMARY KEY ("id")
);

-- CreateTable
-- Matches model StockTransfer in schema.prisma.
-- Nullable fields: dispatchedById, receivedById, dispatchedAt, receivedAt
-- (all filled in progressively as the transfer moves through states).
CREATE TABLE "stock_transfers" (
    "id" TEXT NOT NULL,
    "transferNumber" TEXT NOT NULL,
    "sourceLocationId" TEXT NOT NULL,
    "destLocationId" TEXT NOT NULL,
    "itemId" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL,
    "status" "TransferStatus" NOT NULL DEFAULT 'REQUESTED',
    "notes" TEXT,
    "requestedById" TEXT NOT NULL,
    "dispatchedById" TEXT,
    "receivedById" TEXT,
    "dispatchedAt" TIMESTAMP(3),
    "receivedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "itemName" TEXT NOT NULL,
    "itemSku" TEXT NOT NULL,

    CONSTRAINT "stock_transfers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
-- Matches model CustomerOrder in schema.prisma.
-- confirmedAt and cancelledAt are nullable — set only when those events occur.
CREATE TABLE "customer_orders" (
    "id" TEXT NOT NULL,
    "orderNumber" TEXT NOT NULL,
    "customerName" TEXT NOT NULL,
    "customerPhone" TEXT,
    "locationId" TEXT NOT NULL,
    "status" "OrderStatus" NOT NULL DEFAULT 'PENDING',
    "totalQty" INTEGER NOT NULL DEFAULT 0,
    "notes" TEXT,
    "createdById" TEXT NOT NULL,
    "confirmedAt" TIMESTAMP(3),
    "cancelledAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "customer_orders_pkey" PRIMARY KEY ("id")
);

-- CreateTable
-- Matches model OrderItem in schema.prisma.
-- "itemId" stored directly for query efficiency (redundant with inventoryId→itemId path).
CREATE TABLE "order_items" (
    "id" TEXT NOT NULL,
    "orderId" TEXT NOT NULL,
    "inventoryId" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL,
    "itemName" TEXT NOT NULL,
    "itemSku" TEXT NOT NULL,
    "unitPrice" DECIMAL(10,2) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "itemId" TEXT NOT NULL,

    CONSTRAINT "order_items_pkey" PRIMARY KEY ("id")
);

-- ── Step 3: Create all indexes ────────────────────────────────────────────────
-- Indexes created AFTER tables. PostgreSQL uses B-tree indexes by default.
-- Unique indexes enforce uniqueness AND speed up lookups on those columns.

-- UNIQUE: users.email — one account per email address
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- UNIQUE: locations.name — one location per name
CREATE UNIQUE INDEX "locations_name_key" ON "locations"("name");

-- UNIQUE: items.sku — each product has exactly one SKU
CREATE UNIQUE INDEX "items_sku_key" ON "items"("sku");

-- INDEX: items.sku — explicit index (the unique constraint above already creates
-- an implicit index, but this makes the search optimization intent explicit)
CREATE INDEX "items_sku_idx" ON "items"("sku");

-- INDEX: inventory.itemId — speeds up "find all inventory for item X"
CREATE INDEX "inventory_itemId_idx" ON "inventory"("itemId");

-- INDEX: inventory.locationId — speeds up "find all inventory at location X"
CREATE INDEX "inventory_locationId_idx" ON "inventory"("locationId");

-- UNIQUE COMPOSITE: inventory(itemId, locationId, batchNumber)
-- This is the critical constraint that prevents duplicate inventory rows.
-- One row per (item, location, batch) combination.
-- Uses a composite unique index because all three fields together must be unique.
CREATE UNIQUE INDEX "inventory_itemId_locationId_batchNumber_key" ON "inventory"("itemId", "locationId", "batchNumber");

-- UNIQUE: inventory_transactions.referenceKey
-- The idempotency key. When provided, must be globally unique across all transactions.
-- This prevents duplicate stock movements from retried requests.
CREATE UNIQUE INDEX "inventory_transactions_referenceKey_key" ON "inventory_transactions"("referenceKey");

-- INDEX: inventory_transactions.inventoryId — "all transactions for inventory row X"
CREATE INDEX "inventory_transactions_inventoryId_idx" ON "inventory_transactions"("inventoryId");

-- INDEX: inventory_transactions.createdAt — "transactions between date X and Y"
CREATE INDEX "inventory_transactions_createdAt_idx" ON "inventory_transactions"("createdAt");

-- UNIQUE: work_orders.workOrderNumber
CREATE UNIQUE INDEX "work_orders_workOrderNumber_key" ON "work_orders"("workOrderNumber");

-- INDEX: work_orders.status — "all ASSIGNED work orders"
CREATE INDEX "work_orders_status_idx" ON "work_orders"("status");

-- INDEX: work_orders.locationId — "all work orders at location X"
CREATE INDEX "work_orders_locationId_idx" ON "work_orders"("locationId");

-- UNIQUE: stock_transfers.transferNumber
CREATE UNIQUE INDEX "stock_transfers_transferNumber_key" ON "stock_transfers"("transferNumber");

-- INDEX: stock_transfers.status — "all DISPATCHED transfers"
CREATE INDEX "stock_transfers_status_idx" ON "stock_transfers"("status");

CREATE INDEX "stock_transfers_sourceLocationId_idx" ON "stock_transfers"("sourceLocationId");
CREATE INDEX "stock_transfers_destLocationId_idx" ON "stock_transfers"("destLocationId");

-- UNIQUE: customer_orders.orderNumber
CREATE UNIQUE INDEX "customer_orders_orderNumber_key" ON "customer_orders"("orderNumber");

CREATE INDEX "customer_orders_status_idx" ON "customer_orders"("status");
CREATE INDEX "customer_orders_locationId_idx" ON "customer_orders"("locationId");
CREATE INDEX "order_items_orderId_idx" ON "order_items"("orderId");
CREATE INDEX "order_items_inventoryId_idx" ON "order_items"("inventoryId");

-- ── Step 4: Add foreign key constraints ──────────────────────────────────────
-- Foreign keys are added LAST (after all tables exist) to avoid circular dependency errors.
-- ON DELETE RESTRICT = default for Prisma: cannot delete a referenced row.
--   (e.g., cannot delete an Item that has Inventory rows — must delete Inventory first)
-- ON UPDATE CASCADE = if the referenced id changes, update the foreign key automatically.

-- inventory.itemId → items.id
ALTER TABLE "inventory" ADD CONSTRAINT "inventory_itemId_fkey"
  FOREIGN KEY ("itemId") REFERENCES "items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- inventory.locationId → locations.id
ALTER TABLE "inventory" ADD CONSTRAINT "inventory_locationId_fkey"
  FOREIGN KEY ("locationId") REFERENCES "locations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- inventory_transactions.inventoryId → inventory.id
ALTER TABLE "inventory_transactions" ADD CONSTRAINT "inventory_transactions_inventoryId_fkey"
  FOREIGN KEY ("inventoryId") REFERENCES "inventory"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- inventory_transactions.createdById → users.id
ALTER TABLE "inventory_transactions" ADD CONSTRAINT "inventory_transactions_createdById_fkey"
  FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- work_orders.locationId → locations.id
ALTER TABLE "work_orders" ADD CONSTRAINT "work_orders_locationId_fkey"
  FOREIGN KEY ("locationId") REFERENCES "locations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- work_orders.itemId → items.id
ALTER TABLE "work_orders" ADD CONSTRAINT "work_orders_itemId_fkey"
  FOREIGN KEY ("itemId") REFERENCES "items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- work_orders.assignedToId → users.id (named "AssignedTo" relation)
ALTER TABLE "work_orders" ADD CONSTRAINT "work_orders_assignedToId_fkey"
  FOREIGN KEY ("assignedToId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- work_orders.createdById → users.id (named "CreatedBy" relation)
ALTER TABLE "work_orders" ADD CONSTRAINT "work_orders_createdById_fkey"
  FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- stock_transfers.sourceLocationId → locations.id (named "SourceLocation" relation)
ALTER TABLE "stock_transfers" ADD CONSTRAINT "stock_transfers_sourceLocationId_fkey"
  FOREIGN KEY ("sourceLocationId") REFERENCES "locations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- stock_transfers.destLocationId → locations.id (named "DestLocation" relation)
ALTER TABLE "stock_transfers" ADD CONSTRAINT "stock_transfers_destLocationId_fkey"
  FOREIGN KEY ("destLocationId") REFERENCES "locations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- stock_transfers.itemId → items.id
ALTER TABLE "stock_transfers" ADD CONSTRAINT "stock_transfers_itemId_fkey"
  FOREIGN KEY ("itemId") REFERENCES "items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- stock_transfers.requestedById → users.id
ALTER TABLE "stock_transfers" ADD CONSTRAINT "stock_transfers_requestedById_fkey"
  FOREIGN KEY ("requestedById") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- stock_transfers.dispatchedById → users.id
-- ON DELETE SET NULL because dispatchedById is nullable — if the user is deleted,
-- set the field to NULL rather than preventing the user deletion or cascading.
ALTER TABLE "stock_transfers" ADD CONSTRAINT "stock_transfers_dispatchedById_fkey"
  FOREIGN KEY ("dispatchedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- stock_transfers.receivedById → users.id
ALTER TABLE "stock_transfers" ADD CONSTRAINT "stock_transfers_receivedById_fkey"
  FOREIGN KEY ("receivedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- customer_orders.locationId → locations.id
ALTER TABLE "customer_orders" ADD CONSTRAINT "customer_orders_locationId_fkey"
  FOREIGN KEY ("locationId") REFERENCES "locations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- customer_orders.createdById → users.id
ALTER TABLE "customer_orders" ADD CONSTRAINT "customer_orders_createdById_fkey"
  FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- order_items.orderId → customer_orders.id
-- ON DELETE CASCADE: when a CustomerOrder is deleted, all its OrderItems are automatically deleted.
-- This makes sense — an OrderItem has no meaning without its parent order.
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_orderId_fkey"
  FOREIGN KEY ("orderId") REFERENCES "customer_orders"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- order_items.inventoryId → inventory.id
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_inventoryId_fkey"
  FOREIGN KEY ("inventoryId") REFERENCES "inventory"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- order_items.itemId → items.id
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_itemId_fkey"
  FOREIGN KEY ("itemId") REFERENCES "items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
